export default [{
  "id": 12,
  "name": "player1.kicking",
  "loopType": "none",
  "frames": [{
    "positionX": 251,
    "positionY": 5,
    "width": 73,
    "height": 90
  }, {
    "positionX": 201,
    "positionY": 9,
    "width": 37,
    "height": 82
  }]
}, {
  "id": 11,
  "name": "player2.punching",
  "loopType": "loop",
  "frames": [{
    "positionX": 144,
    "positionY": 220,
    "width": 53,
    "height": 86
  }]
}, {
  "id": 10,
  "name": "player2.walking",
  "loopType": "loop",
  "frames": [{
    "positionX": 973,
    "positionY": 217,
    "width": 22,
    "height": 91
  }, {
    "positionX": 898,
    "positionY": 217,
    "width": 36,
    "height": 89
  }]
}, {
  "id": 9,
  "name": "player2.duckKick",
  "loopType": "none",
  "frames": [{
    "positionX": 695,
    "positionY": 229,
    "width": 36,
    "height": 68
  }, {
    "positionX": 609,
    "positionY": 229,
    "width": 72,
    "height": 68
  }]
}, {
  "id": 8,
  "name": "player2.ducking",
  "loopType": "loop",
  "frames": [{
    "positionX": 552,
    "positionY": 231,
    "width": 50,
    "height": 63
  }]
}, {
  "id": 7,
  "name": "player2.duckPunch",
  "loopType": "loop",
  "frames": [{
    "positionX": 475,
    "positionY": 229,
    "width": 68,
    "height": 68
  }]
}, {
  "id": 6,
  "name": "player2.standing",
  "loopType": "loop",
  "frames": [{
    "positionX": 219,
    "positionY": 222,
    "width": 37,
    "height": 81
  }]
}, {
  "id": 5,
  "name": "player2.kicking",
  "loopType": "none",
  "frames": [{
    "positionX": 337,
    "positionY": 217,
    "width": 75,
    "height": 91
  }, {
    "positionX": 423,
    "positionY": 222,
    "width": 36,
    "height": 81
  }]
}, {
  "id": 4,
  "name": "player2.dead",
  "loopType": "loop",
  "frames": [{
    "positionX": 7,
    "positionY": 226,
    "width": 54,
    "height": 73
  }]
}, {
  "id": 3,
  "name": "player2.hit",
  "loopType": "loop",
  "frames": [{
    "positionX": 84,
    "positionY": 222,
    "width": 38,
    "height": 81
  }]
}, {
  "id": 2,
  "name": "player2.jump",
  "loopType": "loop",
  "frames": [{
    "positionX": 84,
    "positionY": 104,
    "width": 36,
    "height": 91
  }]
}, {
  "id": 1,
  "name": "player2.jumpKick",
  "loopType": "none",
  "frames": [{
    "positionX": 7,
    "positionY": 100,
    "width": 56,
    "height": 99
  }]
}, {
  "id": 0,
  "name": "player1.dead",
  "loopType": "loop",
  "frames": [{
    "positionX": 939,
    "positionY": 14,
    "width": 54,
    "height": 72
  }]
}, {
  "id": 0,
  "name": "player1.hit",
  "loopType": "loop",
  "frames": [{
    "positionX": 880,
    "positionY": 9,
    "width": 36,
    "height": 82
  }]
}, {
  "id": 0,
  "name": "player1.jumpKick",
  "loopType": "none",
  "frames": [{
    "positionX": 735,
    "positionY": 0,
    "width": 55,
    "height": 100
  }]
}, {
  "id": 0,
  "name": "player1.jump",
  "loopType": "loop",
  "frames": [{
    "positionX": 676,
    "positionY": 5,
    "width": 37,
    "height": 90
  }]
}, {
  "id": 0,
  "name": "player1.duckPunch",
  "loopType": "loop",
  "frames": [{
    "positionX": 457,
    "positionY": 16,
    "width": 68,
    "height": 68
  }]
}, {
  "id": 0,
  "name": "player1.duckKick",
  "loopType": "loop",
  "frames": [{
    "positionX": 541,
    "positionY": 16,
    "width": 36,
    "height": 68
  }, {
    "positionX": 590,
    "positionY": 16,
    "width": 73,
    "height": 68
  }]
}, {
  "id": 0,
  "name": "player1.ducking",
  "loopType": "loop",
  "frames": [{
    "positionX": 398,
    "positionY": 18,
    "width": 50,
    "height": 63
  }]
}, {
  "id": 0,
  "name": "player1.punching",
  "loopType": "loop",
  "frames": [{
    "positionX": 330,
    "positionY": 7,
    "width": 52,
    "height": 86
  }]
}, {
  "id": 0,
  "name": "player1.standing",
  "loopType": "loop",
  "frames": [{
    "positionX": 133,
    "positionY": 9,
    "width": 37,
    "height": 82
  }]
}, {
  "id": 0,
  "name": "player1.walking",
  "loopType": "loop",
  "frames": [{
    "positionX": 5,
    "positionY": 5,
    "width": 22,
    "height": 90
  }, {
    "positionX": 66,
    "positionY": 5,
    "width": 36,
    "height": 88
  }]
}];
